### ISSUE TITLE
Source Reference in the Book

### ISSUE THREAD

**Issue by phreed** [rabuf/applied-category-theory#5]
Could you put a links in the book to both the 
* the source the https://github.com/rabuf/applied-category-theory
* the online book https://rabuf.github.io/applied-category-theory

Somewhere in the Introduction would be good.

**Comment by rabuf** [comment]
I've added this information. If you feel it should be formatted or worded differently let me know or provide a pull request with an edit.

If you're satisfied I'll close the issue.

**Comment by phreed** [comment]
That looks good, I am satisfied.
